### ISSUE TITLE
gazebo reported an error [Err] [REST.cc:205] Error in REST request solution

### ISSUE THREAD

**Issue by SamKaiYang** [tku-iarc/timda_dual_arm#9]
![Screenshot 2021-06-24 01:10:48](https://user-images.githubusercontent.com/43115828/123140086-7b597380-d489-11eb-8d62-d2428e5805d9.png)

![Screenshot 2021-06-24 01:16:21](https://user-images.githubusercontent.com/43115828/123140396-d25f4880-d489-11eb-80dd-02a0a298b64f.png)

Modify: .ignition/fuel/config.yaml

ROS:~$ gedit .ignition/fuel/config.yaml

url: https://api.ignitionfuel.org
To
url: https://api.ignitionrobotics.org

**Comment by andy-Chien** [comment]
That's cool
